"""Immutable trading signal directive generated by strategies."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from aditrader.core.models.enums import SignalDirection


class Signal(BaseModel):
    """Normalized strategy signal directive."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    timestamp: datetime = Field(..., description="Generation timestamp in Asia/Kolkata")
    symbol: str = Field(..., min_length=1, description="Target trading instrument symbol")
    direction: SignalDirection = Field(..., description="Action recommendation (BUY, SELL, HOLD)")
    confidence: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Confidence score [0.0, 1.0]"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Contextual diagnostic payload"
    )
